// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyH4xHNCpn_z3_YZr0_4ONuJRONS0VmM4',
    appId: '1:770887237394:android:24f4c7d557e770d52b3dcb',
    messagingSenderId: '770887237394',
    projectId: 'library-books-app-e7a60',
    storageBucket: 'library-books-app-e7a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOMnlGpkBcCkcnVRYSJ4uQ8leEfGyHSKM',
    appId: '1:770887237394:ios:29bdc4b7bc7eb6602b3dcb',
    messagingSenderId: '770887237394',
    projectId: 'library-books-app-e7a60',
    storageBucket: 'library-books-app-e7a60.firebasestorage.app',
    iosBundleId: 'com.example.libraryBooksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkJK0yJJhF5iCpMCGAG2vwXDZX1DiVxAE',
    appId: '1:770887237394:web:37671f079c95a2432b3dcb',
    messagingSenderId: '770887237394',
    projectId: 'library-books-app-e7a60',
    authDomain: 'library-books-app-e7a60.firebaseapp.com',
    storageBucket: 'library-books-app-e7a60.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJK0yJJhF5iCpMCGAG2vwXDZX1DiVxAE',
    appId: '1:770887237394:web:37671f079c95a2432b3dcb',
    messagingSenderId: '770887237394',
    projectId: 'library-books-app-e7a60',
    authDomain: 'library-books-app-e7a60.firebaseapp.com',
    storageBucket: 'library-books-app-e7a60.firebasestorage.app',
  );

}